name: ShiftAndF
main: me.haer0248.saf.Main
version: 1.0.0
api-version: 1.16
author: Haer0248
description: Shift and F run command.
commands:
    saf:
        description: Show about plugin.
permission:
    saf.reload:
        description: reload config.
        default: op