name: ShiftAndF
main: me.haer0248.saf.Main
version: 1.1.0
author: Haer0248
description: Shift and F run command.
commands:
    saf:
        description: Show about plugin.
permission:
    saf.reload:
        description: reload config.
        default: op