name: ShiftAndF
main: me.haer0248.saf.Main
version: 1.2.0
api-version: 1.16
author: NekomataOnigiri
description: Shift and F or Q run command.
commands:
    saf:
        description: Show about plugin.
permission:
    saf.reload:
        description: reload config.
        default: op